#BASICS
mod 'puppetlabs-stdlib',       '4.25.1'
mod 'puppetlabs-concat',       '4.2.1'
mod 'puppetlabs-yumrepo_core', :latest
mod 'puppetlabs-augeas_core',  :latest

#EPEL
mod 'stahnma-epel',            :latest

#PHP
mod 'puppet-php',              '6.0.0'
mod 'puppetlabs-apt',          '4.5.1'
mod 'puppetlabs-inifile',      '2.3.0'
mod 'puppet-zypprepo',         '2.2.1'
mod 'puppet-archive',          '3.2.0'

#NGINX
mod 'puppet-nginx',            :latest

#MYSQL
mod 'puppetlabs-mysql',        :latest
mod 'puppetlabs-translate',    :latest
mod 'puppet-staging',          :latest

# name the module holding the plan so it doesn't get purged by 'bolt module install'
mod 'myapp', local: true
