mod 'puppetlabs-stdlib',            :latest
mod 'puppet-php',                   :latest
mod 'puppet-nginx',                 :latest
mod 'puppetlabs-concat',            :latest
mod 'puppetlabs-mysql',             :latest
mod 'puppetlabs-translate',         :latest
mod 'puppet-staging',               :latest
mod 'dsestero-download_uncompress', :latest

# name the module holding the plan so it doesn't get purged by 'bolt module install'
mod 'myapp', local: true
